### ISSUE TITLE
Report not loading

### ISSUE THREAD

**Issue by RoxaneLS** [nilesh-tawari/ChronQC#5]
Hi Nilesh, I have noticed an issue with ChronQC reports being stuck at the "Loading Report" stage. At first I thought it was a bug in my script or a proxy issue, but then I realised that even older reports that used to open completely fine are stuck now at that stage - and that behaviour is seen on any machine, any browser, within and outside proxies.

See Screenshot attached. As well as the HTML file that used to open fine.

Can you please have a look and see what the problem is?

Many thanks,
Roxane

![screenshot](https://user-images.githubusercontent.com/13159414/67177400-17f88200-f41a-11e9-872b-8a610172c7d8.png)

[Pathology_hyb_PHCP_2.Sample_NA12878.chronqc.17_Dec_2018.html.zip](https://github.com/nilesh-tawari/ChronQC/files/3749045/Pathology_hyb_PHCP_2.Sample_NA12878.chronqc.17_Dec_2018.html.zip)

**Comment by leonorpalmeira** [comment]
Dear @RoxaneLS,

I have experienced the same thing this week. This is due to the `javascript` files being called from inside the `.html` file. These `javascripts` are loaded from different websites and the first one of them is currently giving a 404 error.

The workaround I currently have is to internalize all these `javascript` files and to change the `html` to read the internally downloaded files.

Let me know if you need any help setting this up.

**Comment by RoxaneLS** [comment]
Thank you so much for your answer Leonor. I would very much appreciate your help with this indeed - until Niresh fixes the issue.

How / where did you get those javascript files?

**Comment by leonorpalmeira** [comment]
My current workaround is to edit the `html` file in the section where it loads the `javascript` files from the web, so that it loads files that I provide in an internal folder.

You should open the `html` file, and identify all calls to `http` websites (except the call to ChronQC's github page, that's just an html link). Then download those files in a folder that you can call, let's say, `internalized/`. All you need to do after that is to replace the `http` calls following this example:

- Replace `<script src="https://cdn.rawgit.com/MrRio/jsPDF/master/jspdf.js"></script>`
- By your downloaded file `<script src="internalized/jspdf.js"></script>`

**Comment by leonorpalmeira** [comment]
Dear @RoxaneLS 

I have a question: is your error still reproducible or has it solved itself magically? My old ChronQC files have reverted back to normal behavior even without the tweak I described above. I am not a Javascript expert, so I am not quite sure what was happening here.

Please let me know.

**Comment by nilesh-tawari** [comment]
Hi this seems to be a issue due to missing JavaScript libraries as pointed by @leonorpalmeria  , will work out possible solution and release a fix. Till then we can use offline libraries as mentioned in thread above, only issue with offline libraries is the report is not stand alone.

**Comment by RoxaneLS** [comment]
Thanks both. 

I implemented the workaround suggested by @leonorpalmeira but indeed that is not practical as we can't open the HTML files outside of their original directory now.

Looking fwd to the fix! :)
Thanks.

**Comment by nilesh-tawari** [comment]
The JS libraries are back online, report is now loading normally. Let me know if you still face issues.

**Comment by RoxaneLS** [comment]
Hi Nilesh,
Do you understand why and how the libraries suddenly reappeared? What is
the likelihood of them "disappearing" again?

I would like  to revert back the workaround as it doesn't let us share the
html files alone, but I'm concerned the issue might happen again.

Thanks,
Roxane
